<?xml version="1.0"?>
<package format="3">
  <name>sih_system</name>
  <version>0.1.0</version>
  <description>Master integration and system mission bringup for SIH26177 Search & Rescue.</description>
  <maintainer email="team@sih26177.org">SIH26177 Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>sih_simulation</exec_depend>
  <exec_depend>sih_lidar</exec_depend>
  <exec_depend>sih_perception</exec_depend>
  <exec_depend>sih_mapping</exec_depend>
  <exec_depend>sih_navigation</exec_depend>
  <exec_depend>sih_mission</exec_depend>
  <exec_depend>sih_swarm</exec_depend>
  <exec_depend>sih_dashboard</exec_depend>
  <exec_depend>sih_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
